JeffersonLab/clas12-offline-software

- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/CLASDecoder.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/CodaEventDecoder.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/DetectorEventDecoder.java
> Access BMT data

- common-tools/clas-io/src/main/java/org/jlab/io/hipo/EvioHipoEvent.java
- etc/bankdefs/clas12/FLUX.xml
- etc/bankdefs/hipo/RICH.json
The new GEMC allows to save mirror hits as flux
> Flux banks added for EVIO Output

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/CTOFGeant4Factory.java
- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/SVT/SVTVolumeFactory.java
* removed upstream lightguides from CTOF
* removed region 4 from SVT
> geometry update

- reconstruction/cnd/src/main/java/org/jlab/rec/cnd/costants/Parameters.java
- reconstruction/cnd/src/main/java/org/jlab/rec/cnd/hit/CndHitFinder.java
Modified CND hit reconstruction to remove cuts which killed many events in "calibration mode"
> Modified CND hit reconstruction

- common-tools/clas-detector/src/main/java/org/jlab/detector/base/DetectorType.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorData.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorParticle.java
- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBConstants.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBAnalyzer.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBEngine.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBMatching.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EventBuilder.java
- validation/advanced-tests/run-eb-tests.sh
- validation/advanced-tests/src/eb/EBTwoTrackTest.java
- validation/advanced-tests/src/eb/scripts/gemc-all.sh
- validation/advanced-tests/src/eb/scripts/gemc.csh
- validation/advanced-tests/src/eb/scripts/gen.groovy
- validation/advanced-tests/src/eb/scripts/gen.sh
- validation/advanced-tests/src/eb/scripts/list.txt
bugfix on photon FTOF veto
* was vetoing all photons if any non-charged FTOF hit
* fixed to be only associated hits, but still ~50% so removed veto for now
validation/advanced-tests/eb upgrades
* fiducial cuts in event generator (using org.jlab.clas.fastmc.Clas12FastMC)
* event generator scripts now in this repo
* starting CD and FT tests
starting to import CD matching into PID
> eb-dev updates

- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBUtil.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBAnalyzer.java
- validation/advanced-tests/src/eb/EBTwoTrackTest.java
1-5 GeV, beta>0.9, gamma id inceases by few-%, misid as neutron drops from 10% to ~0
neutron slightly worse than hit-based
> eb: simple ecal timing-based neutron/gamma separation

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/RICHGeant4Factory.java
> RICHGEANT4 Factory modified for GetSTL function

- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/cross/Cross.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/services/CVTReconstruction.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/Cell.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/MakerCA.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/TrackSeederCA.java
New track seeding for CVT.
It modifies the classes CVTReconstruction and Cross
It adds:
- track/Cell.java
- track/MakerCA.java
- track/TrackSeederCA.java
> Adding new CVT seeding algorithm based on cellular automaton.

- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBCCDBConstants.java
- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBUtil.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBAnalyzer.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBEngine.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBMatching.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBRadioFrequency.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EventBuilder.java
EBCCDBConstants no longer used statically.
> eb: fix ccdb handling for multithreading

- reconstruction/ec/src/main/java/org/jlab/service/ec/ECEngine.java
Duplicate lists for ecStrips,ecPeaks,ecClusters objects 
created to avoid thread corruption
> ECEngine Thread Issue

- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/CalorimeterResponse.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/CherenkovResponse.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorData.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorParticle.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorTrack.java
- etc/bankdefs/hipo/EVENT.json
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBAnalyzer.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBEngine.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBTBEngine.java
* disable z-vertex-correction for start time
* reinstating requires reconciliation of FD-CD alignment, or algorithmic changes in EB
* add 3rd moments to REC::Calorimeter
* includes additions to bank format of REC::Calorimeter
* populate REC::Traj from new TimeBasedTrkg::Trajectory
* reformats REC::Traj to coincide with longstanding REC conventions
* tested HTCC-Track matching based on new Trajectory banks
* but fell back to TBT::Tracks.t1*, since that's now sufficiently correct after upstream changes in tracking
> eb updates

- reconstruction/tof/src/main/java/org/jlab/rec/tof/banks/ctof/HitReader.java
- corrected status word for adc=0 hits
- added hit selection to reject hits with both ADCs or TDCs missing
> ctof: corrected status word, added hit selection

- reconstruction/ec/src/main/java/org/jlab/service/ec/ECCommon.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECEngine.java
Move my* structures to ECCommon
Init method for veff (effective velocity)
> Thread Safety

- common-tools/clas-io/src/main/java/org/jlab/utils/CLASResources.java
- reconstruction/dc/src/main/java/org/jlab/rec/dc/trajectory/TrackDictionaryMaker.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/DCHBEngine.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/DCHBEngineCalib.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/DCHBLayerEffsEngine.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/DCTBEngine.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/DCTBLayerEffsEngine.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/TrackingEff.java
geometry database variation for DC reconstruction services is defined via environment variable GEOMETRYDATABASEVARIATION
> geometry database variation is defined via environment variable

- common-tools/cnuphys/ced/src/main/java/cnuphys/ced/geometry/GeometryManager.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagTests.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagneticField.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagneticFieldCanvas.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagneticFields.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/RotatedCompositeField.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/RotatedCompositeProbe.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/Solenoid.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/Torus.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swim/TrajectoryCompare.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swimtest/SwimTest.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swimtest/TestTrajectories.java
Changes to use sector in rotated field and optionally remove solenoid torus overlap
> Changes to use sector in rotated field and optionally remove solenoid torus overlap

- common-tools/cnuphys/ced/src/main/java/cnuphys/ced/item/MagFieldItem.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/CompositeProbe.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/FieldProbe.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagTests.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagneticFieldCanvas.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagneticFields.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/RotatedCompositeField.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/RotatedCompositeProbe.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/Torus.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swim/SectorDerivative.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swim/SwimTrajectory.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swim/Swimmer.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swimZ/SwimZ.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swimtest/SwimTest.java
Swimmer with sector argument for sector CS swimming
> Swimmer with sector argument for sector CS swimming

- common-tools/clas-detector/src/main/java/org/jlab/detector/base/DetectorType.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorData.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorParticle.java
- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBUtil.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBMatching.java
* fix empty REC::Track.chi2
* order CTOF hits by energy
* cleanup DetectorParticle.getHit/Response
* add DetectorType.BAND
> misc event builder updates

- common-tools/cnuphys/ced/src/main/java/cnuphys/ced/item/MagFieldItem.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/Cell2D.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/Cell3D.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/CompositeField.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/CompositeProbe.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/FieldProbe.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/FullTorus.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/IField.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagTests.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagneticField.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagneticFieldCanvas.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagneticFields.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/RotatedCompositeField.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/RotatedCompositeProbe.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/Solenoid.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/Torus.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/ZeroProbe.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swimtest/SerialIO.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swimtest/SwimTest.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swimtest/TestTrajectories.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swimtest/TrajectorySummary.java
> Fixed constructor bug in RotatedCompositeProbe

- reconstruction/ec/src/main/java/org/jlab/service/ec/ECCommon.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECEngine.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECPeak.java
* Set to zero for MC data (assumes FADC = TDC*0.02345)
> TOFFSET moved to CCDB

- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBUtil.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBAnalyzer.java
Only affects (and improves) value of REC::Particle.chi2pid, nothing else.
> eb:  ftof paddle-dependent timing resolution in chi2pid

- reconstruction/cnd/src/main/java/org/jlab/service/cnd/CNDCalibrationEngine.java
As long as there is a cnd hit with status!=0, the status of the cluster is not 0.
The sector, layer, component of the cluster are the sector, layer, component of the hit which has the highest energy deposition.
> Fill status, sector, layer, and component infos into CND::clusters bank

- reconstruction/ec/src/main/java/org/jlab/service/ec/ECCommon.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECEngine.java
Local my* structures and boolean flags accessed only via methods from
ECEngine. By default not accessed in any case unless local=true.
> More thread safety

- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBScalers.java
to resolve NaNs in REC::Event.LT
> EBScalers:  avoid duplication from EBHB+EBTB

- reconstruction/cnd/src/main/java/org/jlab/service/cnd/CNDCalibrationEngine.java
Use Edep-weighted average for the cluster-x, y, z, time.
The resolutions of beta, and theta are slightly better.
Only CNDCalibrationEngine is modified.
> CND clustering: Use Edep-weighted average for the CND_clusters_x, y, z, time

- reconstruction/cnd/src/main/java/org/jlab/rec/cnd/cluster/CNDCluster.java
- reconstruction/cnd/src/main/java/org/jlab/rec/cnd/cluster/CNDClusterFinder.java
- reconstruction/cnd/src/main/java/org/jlab/service/cnd/CNDCalibrationEngine.java
- reconstruction/cnd/src/main/java/org/jlab/service/cnd/CNDEngine.java
the CND clustering code has been moved into a new directory: org/jlab/rec/cnd/cluster.
CNDCalibrationEngine and CNDEngine have been modified accordingly.
No real change of algorithum, but the code is written in a way following clas12 convention, which is more moduling.
added clas12-offline-software/reconstruction/cnd/src/main/java/org/jlab/rec/cnd/cluster/CNDCluster.java
added clas12-offline-software/reconstruction/cnd/src/main/java/org/jlab/rec/cnd/cluster/CNDClusterFinder.java
modified clas12-offline-software/reconstruction/cnd/src/main/java/org/jlab/service/cnd/CNDCalibrationEngine.java
modified clas12-offline-software/reconstruction/cnd/src/main/java/org/jlab/service/cnd/CNDEngine.java
> add a new directory: org/jlab/rec/cnd/cluster

- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/CLASDecoder.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/CodaEventDecoder.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/DetectorDataDgtz.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/DetectorDataFilter.java
- common-tools/clas-utils/src/main/java/org/jlab/utils/data/DataUtils.java
- etc/bankdefs/hipo/DATA.json
- removed slot and channel from VTP banks;
- change RAW:scaler values to long
- fixed bug in timestamp decoding
> Decoder updates for scaler bank, vtp bank and TI timestamp fix

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geom/dc/DCGeantFactory.java
- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geom/dc/GeantFactory.java
- common-tools/coat-lib/deployDistribution.sh
This is the geometry fix for CED.
> fixed the geometry to produce hex cells for CED

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/FTOFGeant4Factory.java
- common-tools/clas-jcsg/src/main/java/org/jlab/detector/volume/Geant4Basic.java
print out to GEMC is trimmed to 4th decimal point.
> Gemc format

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/FTOFGeant4Factory.java
remove lead sheet in front of p1b, and add sheets in front of p1a and p2
> fix the mistake with lead sheets in FTOF

- common-tools/clas-detector/src/main/java/org/jlab/detector/base/DetectorDescriptor.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/CherenkovResponse.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorData.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorResponse.java
> fill sector in REC::Cherenkov

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/PCALGeant4Factory.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/TrackDictionaryMakerRNG.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/TrackDictionaryMerger.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/TrackDictionaryValidation.java
Updated roads dictionary software for the tracking trigger:
- fixes to fastmc based dictionary maker and extension to include PCAL V and W
- updates to MC and data dictionary maker, including extension to HTCC and PCAL V and W
- addition of dictionary merger
- updates to dictionary validation
> Roads devel

- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/services/CVTRecHandler.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/services/CVTReconstruction.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/TrackListFinder.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/TrackSeederCA.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/fit/KFitter.java
please, pay attentions at my comments for the two commits
> CVT: ccdb, chi2 and seeding

- .travis.yml
- build-coatjava.sh
To what people normally use, nospotbugs and nounittests.  Keep travis tests unchanged.
> Change build script default options

- common-tools/clas-analysis/src/main/java/org/jlab/analysis/physics/TestEvent.java
- etc/services/data.yaml
- etc/services/dst.yaml
- etc/services/mc.yaml
- etc/services/reconstruction.yaml
- reconstruction/dc/src/main/java/org/jlab/rec/dc/Constants.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/DCEngine.java
- reconstruction/dc/src/test/java/org/jlab/service/dc/DCReconstructionTest.java
- updated DC unit test based on installation geometry after CCDB default variation update
- DC wire distortion set to false by default
- DC use of start time in TBT set to true by default
> Updated DC unit test and default values of DC yaml/environment variables

- common-tools/clas-io/src/main/java/org/jlab/io/hipo/HipoDataEvent.java
As Spanish say - "Voila", I fixed the removeBank and removeBanks in DataEvent's
Hipo implementation.
> added implementation for removeBank and removeBanks in HipoDataEvent.

- common-tools/clas-reco/src/main/java/org/jlab/clas/reco/io/EvioHipoEvent4.java
Was fixed in hipo3 during the hipo3-4 transition but not transferred
> fixed parent/daugther variables names in LUND bank conversion

- common-tools/clas-io/src/main/java/org/jlab/io/hipo/HipoDataSource.java
Now you can go to any event in HipoDataSource.
> implemented method gotoEvent in HipoDataSource

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/volume/Geant4Basic.java
increase the number of fraction digits for small numbers to accommodate the small values in translations and rotations after alignment
> Gemc precision

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/CTOFGeant4Factory.java
- common-tools/clas-jcsg/src/main/java/org/jlab/detector/volume/Geant4Basic.java
change default precision in gemc output to 7 decimals
> change default precision in gemc output to 7 decimals

- bin/dst-maker
- bin/recon-util
- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicitySequenceManager.java
* reduce memory usage on recon-util
* add dst-maker script
* overload some helicity getters
> Script and helicity updates

- bin/decoder
( pending memory leak fix before reducing limits ...)
> fix mistake on decoder memory limit

- reconstruction/dc/src/main/java/org/jlab/service/dc/TrackDictionaryValidation.java
- updated code to get HTCC Cherenkov angles from x,y,z coordinates;
- fix bug in relating particles to tracks
> update of dict-validate to cope with bank changes

- reconstruction/tof/src/main/java/org/jlab/rec/tof/banks/ftof/HitReader.java
- reconstruction/tof/src/main/java/org/jlab/rec/tof/hit/AHit.java
- reconstruction/tof/src/main/java/org/jlab/rec/tof/hit/IGetCalibrationParams.java
- reconstruction/tof/src/main/java/org/jlab/rec/tof/hit/ctof/Hit.java
- reconstruction/tof/src/main/java/org/jlab/rec/tof/hit/ftof/Hit.java
- reconstruction/tof/src/main/java/org/jlab/service/ftof/FTOFEngine.java
- new TW correction for FTOF based on the functional tw1*exp(tw2*energy)+tw3/energy
- constants read from CCDB /calibration/ftof/time_walk_exp
- old/new TW correction enabled or disable via tw0 constant (ensures compatibility with MC)
> Implementation of new FTOF TW functional

- common-tools/clas-analysis/src/main/java/org/jlab/analysis/physics/TestEvent.java
- reconstruction/dc/src/test/java/org/jlab/service/dc/DCReconstructionTest.java
Updated 7 month old DC unit test with tighter cuts which better represent newer versions as per Veronique's suggestion
Michael Armstrong
> DC unit test update

- common-tools/clas-detector/src/main/java/org/jlab/detector/base/GeometryFactory.java
- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/SVT/SVTConstants.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorData.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/Constants.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/bmt/CCDBConstantsLoader.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/services/CVTReconstruction.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/fit/StateVecs.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/trajectory/TrajectoryFinder.java
- corrected CVT vx, vy coordinates in EB
- first optimization of trajectories for CVT
- fix to CD/target shift
> Cvt traj swim

- common-tools/clas-reco/src/main/java/org/jlab/clas/reco/io/EvioHipoEvent4.java
- etc/bankdefs/clas12/RTPC.xml
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/banks/HitReader.java
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/HelixFitTest.java
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/HitParameters.java
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/HitVector.java
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/RecoHitVector.java
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/TrackDisentangler.java
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/TrackFinder.java
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/TrackHitReco.java
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/TrackUtils.java
- reconstruction/rtpc/src/main/java/org/jlab/service/rtpc/RTPCEngine.java
Includes changes to support CCDB constants, and new reconstruction formula
> RTPC CCDB Update

- etc/bankdefs/hipo4/rtpc.json
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/HitParameters.java
- reconstruction/rtpc/src/main/java/org/jlab/rec/rtpc/hit/TrackHitReco.java
Updates to reconstruction and hit parameters to read in new parameter from CCDB. Also changed rtpc reconstruction bank group and item numbers to match other detector schemes.
> added support to turn off time shift

- common-tools/clas-geometry/src/main/java/org/jlab/geom/prim/Vector3D.java
- etc/bankdefs/hipo4/rich.json
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHConstants.java
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHEBEngine.java
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHEvent.java
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHEventBuilder.java
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHHit.java
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHLayer.java
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHParticle.java
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHSolution.java
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHTool.java
- reconstruction/rich/src/main/java/org/jlab/rec/rich/RICHio.java
New rich software release with
- planes for trajectory definition
- new output bank (Cherenkov information per track)
- new CCDB tables (pixel properties and calibrated values from electron control sample)
- consistent n-angle treatment in the tracing algorithm
> Hipo4 rich dev

- etc/bankdefs/hipo4/cnd.json
- reconstruction/cnd/src/main/java/org/jlab/rec/cnd/cluster/CNDCluster.java
- reconstruction/cnd/src/main/java/org/jlab/rec/cnd/cluster/CNDClusterFinder.java
- reconstruction/cnd/src/main/java/org/jlab/service/cnd/CNDCalibrationEngine.java
this is to be able to compute de/dx for CND clusters in scintillator response
> added path length through bar for CND clusters

- reconstruction/eb/src/main/java/org/jlab/service/eb/EBAnalyzer.java
> assign neutral momentum (to zero) even if no start time

- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicityState.java
> fix missing helicity FADC readouts *before* inversion

- build-coatjava.sh
- common-tools/clas-analysis/pom.xml
- common-tools/clas-analysis/src/main/java/org/jlab/analysis/postprocess/Tag1ToEvent.java
- common-tools/clas-io/pom.xml
- common-tools/clas-io/src/main/java/org/jlab/utils/JsonUtils.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/reco/EngineProcessor.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/reco/ReconstructionEngine.java
- common-tools/coat-lib/pom.xml
- etc/bankdefs/hipo4/header.json
- reconstruction/band/pom.xml
- reconstruction/cnd/pom.xml
- reconstruction/cvt/pom.xml
- reconstruction/dc/pom.xml
- reconstruction/eb/pom.xml
- reconstruction/eb/src/main/java/org/jlab/rec/eb/Versions.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/VersionEngine.java
- reconstruction/ec/pom.xml
- reconstruction/ft/pom.xml
- reconstruction/fvt/pom.xml
- reconstruction/htcc/pom.xml
- reconstruction/ltcc/pom.xml
- reconstruction/rich/pom.xml
- reconstruction/rtpc/pom.xml
- reconstruction/swaps/pom.xml
- reconstruction/tof/pom.xml
* Modify all poms to include version numbers in jar manifests
* Add JsonUtils convenience class for reading/writing/appending a JSON bank
* Add YAML filterer for recon-util to emulate the EngineData that services receive from CLARA
* Create/append COAT::config bank by all ReconstructionEngines
* including service/coatjava versions and YAML contents
* Copy COAT::config to new tag-1 event in postprocessing
> Add and fill software configuration bank

- common-tools/clas-io/pom.xml
- common-tools/clas-io/src/main/java/org/jlab/io/evio/EvioDataBucket.java
- common-tools/clas-io/src/main/java/org/jlab/io/utils/EvioCure.java
Reverts JeffersonLab/clas12-offline-software#639
* mistakently assumed it was to an issue branch and not development, needs to be reverted
> Revert "Iss638 evio"

- common-tools/clas-detector/pom.xml
- common-tools/clas-io/pom.xml
- common-tools/clas-io/src/main/java/org/jlab/io/evio/EvioDataBucket.java
- common-tools/clas-io/src/main/java/org/jlab/io/utils/EvioCure.java
- common-tools/coat-lib/pom.xml
* fixes issue reading some BONuS data
* required adapting to EVIO API changes
* maven changes for new third-party, local EVIO dependencies 
* also in EVIO's maven build:  https://github.com/JeffersonLab/evio/commit/b6c6849e6efdfa3bacaf03baa87b9b1a92519c60
* includes hipo4 4.0->4.1 and hipo 1.1->2.0 (to keep same evio version)
> evio 6.1->6.2

- .github/workflows/maven.yml
- build-coatjava.sh
- validation/advanced-tests/run-advanced-tests.sh
- validation/advanced-tests/run-eb-tests.sh
> Convert Travis to github actions

- common-tools/clas-io/src/main/java/org/jlab/io/hipo/HipoDataSource.java
- common-tools/clas-io/src/main/java/org/jlab/io/hipo/HipoDataSync.java
The back end of HipoDataSync is now tagged hipo writer. so events that are written will be arranged in buckets according to their tags.
> changes in HipoDataSync.

- common-tools/clas-detector/src/main/java/org/jlab/detector/calib/utils/ConstantsManager.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/reco/ReconstructionEngine.java
- common-tools/swim-tools/src/main/java/org/jlab/clas/swimtools/MagFieldsEngine.java
> Iss572 abort

- common-tools/cnuphys/magfield/src/main/java/cnuphys/bin/build.xml
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/Cell3D.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/FastMath.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/GEMCCompare.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagTests.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/MagneticFields.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/TorusProbe.java
- common-tools/cnuphys/magfield/src/main/java/cnuphys/magfield/converter/Converter.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/adaptiveSwim/AAdaptiveStopper.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/adaptiveSwim/AdaptiveRhoStopper.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/adaptiveSwim/AdaptiveSStopper.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/adaptiveSwim/AdaptiveSwimResult.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/adaptiveSwim/AdaptiveSwimUtilities.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/adaptiveSwim/AdaptiveSwimmer.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/adaptiveSwim/ButcherAdvance.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/adaptiveSwim/IAdaptiveStopper.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/adaptiveSwim/RK4HalfStepAdvance.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/lund/LundTrackDialog.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swim/DefaultRhoStopper.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swim/SwimTrajectory.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swim/Swimmer.java
- common-tools/cnuphys/swimmer/src/main/java/cnuphys/swimtest/SwimTest.java
Fixed a bug in the old swimmer swimRho method. Cleaned up and improved the new swimmer; trying to get it closer to adoption. Modified the "swim a particle" dialog in ced to have a third option  of swim to "fixed rho" for testing, which might be useful for central detector displays.
> Swim rho test

- reconstruction/ec/src/main/java/org/jlab/service/ec/ECCommon.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECEngine.java
Implement status knockout of strips for status 2 (TDC) and 3 (ADC/TDC).
> Iss618 statuses

- common-tools/clas-reco/src/main/java/org/jlab/clas/reco/ReconstructionEngine.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBEngine.java
* and removed that functionality from EBEngine
> add drop banks to ReconstructionEngine

- common-tools/clas-detector/src/main/java/org/jlab/detector/calib/utils/ConstantsManager.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/calib/utils/DatabaseConstantProvider.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/reco/ReconstructionEngine.java
- common-tools/clas-utils/src/main/java/org/jlab/utils/groups/IndexedList.java
* unlimited in ConstantsManager, DatabaseConstantProvider, ReconstructionEngine
* limited to 4 by (at least) IndexedList, which now throws an exception otherwise
> Add support for more table indices

- .github/workflows/maven.yml
- build-coatjava.sh
> Stop removing parts of local maven repo in build script

- bin/bg-merger
- bin/bos2hipo
- bin/daqEventViewer
- bin/dclayereffs-ana
- bin/decoder
- bin/dict-maker
- bin/dict-merge
- bin/dict-validate
- bin/evio2hipo
- bin/eviocure
- bin/eviodump
- bin/hadd
- bin/hipo-browser
- bin/hipo-utils
- bin/postprocess
- bin/rebuild-scalers
- bin/recon-util
- bin/run-groovy
- bin/trigger-filter
- bin/trigger-splitter
> Switch to serial GC for single-threaded stuff used in batch jobs
