- reconstruction/ec/src/main/java/org/jlab/service/ec/ECCommon.java
Fixed strip and peak threshold bug. Scale factors introduced to match actual FADC energy scale for both KPP data and GEMC 2.5. Previous settings applied only to MC data from GEMC 2.4.  This means thresholds were x10 too low for any data other than GEMC 2.4 derived MC data.
> ECCommon.java

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/SVT/SVTConstants.java
- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/SVT/SVTStripFactory.java
Mismatch between call to getIdealStrip (RSSM) in getShiftedStrip and getIdealStrip method itself (RSMS) meant getShiftedStrip did not work. Changed all instances of RSSM ordering to RSMS for consistency.
> aRegion, aSector, aModule, aStrip mismatch

- reconstruction/ltcc/src/main/java/org/jlab/service/ltcc/LTCCHit.java
- reconstruction/ltcc/src/main/java/org/jlab/service/ltcc/viewer/LTCCClusterHistos.java
- reconstruction/ltcc/src/main/java/org/jlab/service/ltcc/viewer/LTCCHistogrammer.java
- reconstruction/ltcc/src/main/java/org/jlab/service/ltcc/viewer/LTCCHitHistos.java
- reconstruction/ltcc/src/main/java/org/jlab/service/ltcc/viewer/LTCCViewer.java
Each LTCC PMT has 3 unique identifiers: (sector, segment, side). This used to be encoded in the (sector, component, layer) fields, but was recently changed to be (sector, component, order) instead in the decoded data files. This pull requests updates the LTCC reconstruction code to reflect these changes. It also includes a minor refactoring of the LTCC reconstuction debug viewer.
Note regarding simulation:
I'm unsure if the EVIO-HIPO converter was updated for this change, meaning that there might be an issue when converting GEMC-generated EVIO files 
(See clas-reco/src/main/java/org/jlab/clas/reco/io/EvioHipoEvent.java line 143)
hipoBank.setByte("layer", i, (byte) evioBank.getInt("side",i));
> CRITICAL: LTCC side now correctly detected

- reconstruction/ec/src/main/java/org/jlab/service/ec/ECEngine.java
- reconstruction/tof/src/main/java/org/jlab/service/ctof/CTOFEngine.java
- reconstruction/tof/src/main/java/org/jlab/service/ftof/FTOFEngine.java
If run<=0, print message and ignore event, instead of generating less informative errors (e.g. from ConstantsManager.getConstants).
This happens at the beginning of real data runs before raw header banks get filled properly.
Other engines may have similar "issues", but behavior depends on run ranges populated in ccdb for each system.
> EC/CTOF/FTOFEngine:  handle RUN::config.run=0 more gracefully

- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBCCDBConstants.java
- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBUtil.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBEngine.java
In support of upcoming run-dependent RF calibrations.
Note, usage of EventBuilder outside the standard service chain will now require choosing a valid run number and calling `EBEngine.init(int run)` instead of `EBEngine.init()`.  Previously the default run number was 10.
> eb:  use RUN::config.run for ccdb

- common-tools/clas-jcsg/src/main/java/org/jlab/detector/geant4/v2/CTOFGeant4Factory.java
- reconstruction/tof/src/main/java/org/jlab/rec/ctof/Constants.java
- reconstruction/tof/src/main/java/org/jlab/rec/tof/banks/ctof/HitReader.java
- reconstruction/tof/src/main/java/org/jlab/rec/tof/hit/ctof/Hit.java
- reconstruction/tof/src/main/java/org/jlab/service/ctof/CTOFEngine.java
- update key geometry parameter values in jcsg to match latest values from CAD
- removed hardcoded geometry parameters in reco package, now using only info from jcsg geometry
- corrected calculation of y_offset in reco (longitudinal offset of the ctof paddle with respect to CLAS12 paddle)
> CTOF geometry: update of key geometry parameters and fixed offset calculation in reco

- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/CherenkovResponse.java
At least partially the culprit for pid=11 depletion in phi-midsector of S4.
> CherenkovResponse:  bugfix on delta-phi wrapping

- .gitignore
- bin/decoder
- bin/env.sh
- build-coatjava.sh
- etc/services/reconstruction.yaml
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/trajectory/TrkSwimmer.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBEngine.java
- validation/advanced-tests/run-eb-tests.sh
- validation/etc
- validation/unit-tests/run-unit-tests.sh
* All maps renamed with specific names and documented
* All maps now stored in the official public repository
* That repository is now at JLab instead of github (due to filesize limitations)
* https://clasweb.jlab.org/clas12offline/magfield, see README
* Currently all maps are retrieved by the build script
* but only if necessary,  i.e. newer timestamp or filesize different than existing local copy
* Default torus map in software is now the latest and greatest one
* `Symm_torus_r2501_phi16_z251_24Apr2018.dat`
* Changing the choice of maps is now located in only 2 files:
* `etc/services/reconstruction.yaml` for CLARA
* `bin/env.sh` for standalone
* (plus minor, unrelated EB changes for dropping banks)
> Reorganization of magnetic field maps

- common-tools/cnuphys/parent/pom.xml
This speeds up the spotbugs check and produces fewer (non-serious) warnings/errors
> cnuphys no longer ignores spotbugs-exclude.xml

- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/banks/RecoBankWriter.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/services/CVTRecHandler.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/services/CVTReconstruction.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/TrackSeeder.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/TrackSeederCA.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/fit/KFitter.java
Changes:
- CVT service modified. Most of the code has been put in a separate class "CVTRecHandler", so that can be used also by other classes/analyses.
- An old fix to the old seeding algorithm
- small changes to CA seeder
- added a method to KFitter: init does not need the svt geo, but for retro-compatibility, the old one is still there
> CVT: refactor service and small fixes

- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/cross/Cross.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/fit/HelicalTrackFitter.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/services/CVTRecHandler.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/MakerCA.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/Seed.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/Track.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/TrackListFinder.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/TrackSeederCA.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/track/fit/KFitter.java
- reconstruction/cvt/src/main/java/org/jlab/rec/cvt/trajectory/TrajectoryFinder.java
Small fix:
- Trajectory filling fixed. Now the intersections with the detector planes is filled regardless of the presence of a cross in the plane. Duplicate entries in the trajectory also fixed.
- Cross's compareTo method improved to take into account same layer bmt crosses
- Cross position at the Track fixed for better display in CED.
New feature:
- Track now extend comparable and has a hashCode method. This allows one to simplify the search in arrays. Old methods will be removed in future.
- Clone killing. Candidates are considered clones if they share at least 2 crosses. Duplicate choice based on the largest number of crosses.
> CVT tracking. Improvements to the algo and clone killing switched on.

- reconstruction/ec/src/main/java/org/jlab/service/ec/ECCommon.java
- validation/advanced-tests/src/eb/EBTwoTrackTest.java
* too tight for mc, causing neutral eb pid tests to fail miserably
> ec:  revert tightened time matching cut

- common-tools/clas-io/src/main/java/org/jlab/io/evio/EvioETSource.java
Sometimes ET stations are created with non-default TCP port numbers.  This constructor allows online monitors to customize connection parameters.
> EvioETSource: Add constructor with port option

- reconstruction/dc/src/main/java/org/jlab/rec/dc/banks/HitReader.java
- reconstruction/dc/src/main/java/org/jlab/rec/dc/cluster/ClusterCleanerUtilities.java
- reconstruction/dc/src/main/java/org/jlab/rec/dc/cluster/ClusterFinder.java
- reconstruction/dc/src/main/java/org/jlab/rec/dc/timetodistance/TimeToDistanceEstimator.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/DCHBEngine.java
I think that the issue observed in the doca vs time plot is due to hits with reset LR ambiguity for which the B-field information did not get persisted.  This fix ensures this.  The status=2 for times greater that tmax is removed.  I would like to test this code for calibrations.
> Set B-field values to hits resolved from LR ambiguity algo.

- reconstruction/cvt/src/test/java/org/jlab/rec/cvt/services/CVTReconstructionTest.java
Ranges for the unit test are 3 sigma from the centroid from current gemc simulation. Distributions for each unit test are shown below.
> commit -m "Revised cuts on unit tests." CVTReconstructionTest.java

- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorHeader.java
- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBCCDBConstants.java
- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBCCDBEnum.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBio.java
Uses CCDB's /runcontrol/hwp, https://clasweb.jlab.org/cgi-bin/ccdb/versions?table=/runcontrol/hwp
CCDB values are up to date by Harut for RG-A and RG-K and simulation.
Addresses issue #227
> correct helicity for hwp, finalize helicity convention at -1/0/1 = -/UDF/+

- reconstruction/ec/src/main/java/org/jlab/service/ec/ECCommon.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECEngine.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECPeak.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECStrip.java
- reconstruction/ec/src/test/java/org/jlab/service/ec/ECReconstructionTest.java
All changes compatible with GEMC and previous release
o Global timewalk correction now used in FADC-TDC calculation
o FADC-TDC offsets now at both global and local (PMT) level
o FADC-TDC cuts reduced from 30 ns to 10 ns.
o /calibration/ec/tdc_global_offset initialized
o /calibration/ec/tmf_offset initialized
o /calibration/ec/tmf_window initialized
o Replace hardcoded TDC-fADC window cut with CCDB tmf_window
o Implement /calibration/ec/tdc_global_offset
> Updates to TDC-FADC time matching

- common-tools/clas-analysis/src/main/java/org/jlab/analysis/physics/TestEvent.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/CLASDecoder4.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorData.java
- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorHeader.java
- etc/bankdefs/hipo4/data.json
- etc/bankdefs/hipo4/event.json
- etc/bankdefs/hipo4/header.json
- reconstruction/dc/src/main/java/org/jlab/rec/dc/banks/HitReader.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/DCTBEngine.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/LayerEfficiencyAnalyzer.java
- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBCCDBConstants.java
- reconstruction/eb/src/main/java/org/jlab/rec/eb/EBCCDBEnum.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBio.java
- validation/advanced-tests/src/eb/EBTwoTrackTest.java
* Move RUN::config.helicityL3 to new bank, HEL::online
* Remove REC::Traj.q
* Rename REC::Event variables
* STTime to startTime
* BCG to beamCharge
* LT to liveTime
* EvCat to category
* NPGP to topology
* PTIME to procTime
* Helic to helicity
* Remove REC::Event variables
* EVNTime
* TYPE
* TRG
* Only fill REC::Event.helicity if non-delayed for now (based on CCDB's /runcontrol/helicity)
> Last DST bank changes

- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicityAnalysis.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicityBit.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicityGenerator.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicitySequence.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicitySequenceDelayed.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicityState.java
* accommodate HWP during analysis
* switch quartet/sync method names to the more proper patternSync/pairSync
* move analysis example to dedicated class
* switch public getters to all return HelicityBit instead of combo of State/Bit
* cleanup javadocs
> Helicity Analysis updates

- common-tools/clas-reco/src/main/java/org/jlab/clas/detector/DetectorParticle.java
- reconstruction/eb/src/main/java/org/jlab/service/eb/EBEngine.java
1. Trigger Particle
2. Negatives
3. Positives
4. Neutrals
And then momentum-ordered with groups 2/3/4.
RECFT::Particle still maintains the same row-ordering as REC::Particle.
> Turn on REC::Particle sorting

- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/DaqScalers.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/DaqScalersSequence.java
For easy access to pseudo-event-based beam charge for RG-A post-processing.
> Add timestamp-based lookup of most recent tag=1 RUN::scaler bank

- .travis.yml
- common-tools/clas-geometry/pom.xml
- common-tools/clas-io/pom.xml
- common-tools/clas-jcsg/pom.xml
- common-tools/cnuphys/bCNU/pom.xml
- common-tools/cnuphys/parent/pom.xml
- parent/pom.xml
Update our travis build configuration to be compatible with ubuntu 16/xenial
* in the last couple weeks our new branches appear to now be automatically selecting xenial in travis (and failing), while our main branch (development) is still running 14/trusty (and succeeding), although we do not specify an ubuntu version in our travis config
* this is presumably consistent with travis's move to xenial and dropping support for trusty: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment, and so we should follow suit and get compatible with xenial
* this requires:
* upgrading to a jdk version 10/11 and maven to 1.6 to use stock 16/xenial packages
* this pull request chooses openjdk11
* updating our pom.xmls
* explicitly including dependencies that were previously in the jdk …
> travis upgrade

- bin/recon-util
This reverts commit f060779cf55834536900551677e7fe8f039042ca.
Looks like performance testing was with java 11 ...
> Revert "reduce memory limit on recon-util (10% faster!?)"

- bin/.postprocess
- common-tools/clas-analysis/src/main/java/org/jlab/analysis/postprocess/Tag1ToEvent.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicitySequenceManager.java
* import RG-A post-processing from Will
* inserts delayed helicity and beamCharge/liveTime into REC::Event
* input files must still be from a single run number (due to limitations in org.jlab.detector.decode.DaqScalersSequence)
> standardize postprocessing

- common-tools/swim-tools/src/main/java/org/jlab/clas/swimtools/Swim.java
to recover tracks whose vertex is very far upstream. The change is relevant for swimming to FMT planes since they are relatively close to the CLAS12 center. The change was tested on data finding no impact on the processing time.
> SwimToBoundayPlane: removing check on track vertex

- bin/bos2hipo
- bin/daqEventViewer
- bin/dclayereffs-ana
- bin/decoder
- bin/dict-maker
- bin/dict-merge
- bin/dict-validate
- bin/env.sh
- bin/evio-viewer
- bin/evio2hipo
- bin/eviocure
- bin/eviodump
- bin/hadd
- bin/hipo-browser
- bin/hipo-utils
- bin/kpp-plots
- bin/mon12
- bin/postprocess
- bin/rebuild-scalers
- bin/recon-util
- bin/run-groovy
Ubuntu comes with /bin/sh pointing to dash, which doesn't support bash's "source".  (Could also switch all /bin/sh scripts to explicitly /bin/bash, not sure which is better.)
> remove bashisms from /bin/sh scripts (plus cleanup)

- etc/bankdefs/hipo4/ecal.json
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECCommon.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECEngine.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECPeak.java
- reconstruction/ec/src/main/java/org/jlab/service/ec/ECStrip.java
- reconstruction/mc/pom.xml
* variable "id" in the ECAL::hits bank is filled to represent the ADC row number of corresponding hit in ADC bank,
* the variable "clusterId" is added in the ECAL::hits bank, it points to the cluster row number of the cluster (to which the hit belongs to) in the ECAL::clusters bank.
Sorry the netbeans automatically formatted the  ECEngine file,
if this is an issue, I can check it out again, and add my modification.
> Iss551 ecal hit and cluster ids

- build-coatjava.sh
to avoid confusion with multiple simultaneous versions
> mvn clean coat-lib in build script

- common-tools/clas-analysis/src/main/java/org/jlab/analysis/postprocess/Tag1ToEvent.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/decode/DaqScalersSequence.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicitySequenceManager.java
- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicityState.java
* flip offline helicity at transition from `HEL::adc` to `HEL:flip` during decoding
* based on well-known physics reactions measured by CLAS12
* still unknown where the sign convention is broken, online or offline
* note that `HEL:adc` is left with the old convention, as it's a raw FADC voltage value
* provides post-processing methods to preform the flip in previously decoded data
* both `HEL::flip` and `REC::Event  `
> Iss582 helflip

- reconstruction/dc/src/main/java/org/jlab/rec/dc/track/TrackCandListFinder.java
- reconstruction/dc/src/main/java/org/jlab/service/dc/DCTBEngine.java
Set fail flag for track not swimmable to reference surfaces used for EB matching to detectors.
Pass only tracks with on-fail flag.
> Return for tracks not swimmable to HTCC sphere.

- common-tools/clas-utils/src/main/java/org/jlab/utils/groups/IndexedTable.java
Also, FYI, looks like setIntValue may not work.
> bugfix for IndexedTable when #indices!=3

- .github/workflows/maven.yml
The --quiet got dropped when moving from Travis to Github Actions
> Make CI logs less noisy

- common-tools/clas-detector/src/main/java/org/jlab/detector/helicity/HelicitySequence.java
This happened in BONuS, when the DAQ wrote a few events with the wrong run number, e.g. run 12069 somewhere in files 00005-00009.
> accommodate no helicity states found

- common-tools/coat-lib/pom.xml
- maven-settings.xml
to what HPS uses, and java.freehep.org is down and a recurring problem, address #738
> update freehep maven urls

- build-coatjava.sh
Noticed that -h was printing `build-coatjava.sh a a a a`, and the double-quotes fixes that.
> Fix usage printout in build script
